### PR TITLE
Fixes #798 - patches Cinder to be able to fall back to a configured AZ

### LINKED ISSUE #798: Launching instances with newly cloned volumes when specifying an AZ fails
The genesis of this bug is the work done in #768, combined with a change that went into Kilo (https://review.openstack.org/#/c/157041). With multiple-AZ clusters now, we removed the availability zone from Cinder. If no availability zone is specified, things will work as expected. If an availability zone is specified, Nova will pass that AZ through to Cinder, which will attempt (and fail) to validate it, tanking the instance launch. Removing the AvailabilityZoneFilter from the Cinder scheduler does _not_ resolve the issue.

A workaround is to clone the root volume from an image via `cinder create` or Horizon prior to launching the instance, then passing that volume to Nova as the root volume. Specifying a compute AZ will work if the volume is already created.

### PR DESCRIPTION
**Pull request by erhudy**
This PR allows Cinder to work properly in our configuration with no storage availability zones configured, as we manage that through Ceph.

To test:
* with `['bcpc']['cinder']['az_fallback']` set to **false** (the current behavior in upstream OpenStack), executing `cinder create --availability-zone Test-Laptop-Vagrant --display-name blah 10` will fail; setting to **true** will trigger the patch code and the volume creation should then work (`cinder-api.log` will indicate that it's hit the condition by printing out `Availability zone 'BLAH-1' not found, falling back to ''`)
* `nova boot` commands that specify `--block-device` for creation of a root volume at instance start should similarly fail on **false** and work on **true**

This patch will get upstreamed to OpenStack once I have written unit tests.

### CODE REVIEW

File: cookbooks/bcpc/attributes/default.rb [hunk 1]
```diff
@@ -586,7 +586,7 @@
   "compute:reboot" => "rule:admin_or_owner",
   "compute:delete" => "rule:admin_or_owner",
   "compute:unlock_override" => "rule:admin_api",
-  
+
```
Comment (erhudy) [inline cookbooks/bcpc/attributes/default.rb]: I think Atom removed spaces from these and the lines below when saving.

File: cookbooks/bcpc/files/default/cinder_availability_zone_fallback.patch [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+@@ -327,10 +327,21 @@ class ExtractVolumeRequestTask(flow_utils.CinderTask):
+             else:
+                 # For backwards compatibility use the storage_availability_zone
+                 availability_zone = CONF.storage_availability_zone
++
+         if availability_zone not in self.availability_zones:
+-            msg = _("Availability zone '%s' is invalid") % (availability_zone)
+-            LOG.warn(msg)
+-            raise exception.InvalidInput(reason=msg)
++            if CONF.allow_availability_zone_fallback:
```
Comment (erhudy) [inline cookbooks/bcpc/files/default/cinder_availability_zone_fallback.patch]: This is my patch code; if the config option is set, it will revert to `default_availability_zone` (`None` by default) and then to `storage_availability_zone` (`nova` by default).

**Comment by erhudy** [comment]
Upstreamed to OpenStack at https://bugs.launchpad.net/cinder/+bug/1489575.

**Comment by kamidzi** [comment]
The first part of this works as advertised. Please provide an explicit example of nova boot command using `--boot-device` that exercises the patch as I could not contrive one, whether a result of my environment or otherwise.

**Comment by erhudy** [comment]
This sequence will exercise the patch.

With `['bcpc']['cinder']['az_fallback']` set to **true** and all daemons in a good state, using the ID of the Cirros image and the name of an availability zone as given by `nova availability-zone-list`:
```
root@bcpc-vm1:~# glance image-list
+--------------------------------------+---------------------+
| ID                                   | Name                |
+--------------------------------------+---------------------+
| 01837847-09cc-4cf1-8fa3-a8986928d887 | Cirros 0.3.4 x86_64 |
+--------------------------------------+---------------------+
root@bcpc-vm1:/var/log/cinder# nova availability-zone-list 
+-----------------------+----------------------------------------+
| Name                  | Status                                 |
+-----------------------+----------------------------------------+
| internal              | available                              |
| |- bcpc-vm1           |                                        |
| | |- nova-conductor   | enabled :-) 2015-08-28T22:40:17.000000 |
| | |- nova-scheduler   | enabled :-) 2015-08-28T22:40:19.000000 |
| | |- nova-consoleauth | enabled :-) 2015-08-28T22:40:18.000000 |
| | |- nova-cert        | enabled :-) 2015-08-28T22:40:26.000000 |
| | |- nova-network     | enabled :-) 2015-08-28T22:40:25.000000 |
| |- bcpc-vm2           |                                        |
| | |- nova-network     | enabled :-) 2015-08-28T22:40:20.000000 |
| |- bcpc-vm3           |                                        |
| | |- nova-network     | enabled :-) 2015-08-28T22:40:23.000000 |
| TLVM-1                | available                              |
| |- bcpc-vm1           |                                        |
| | |- nova-compute     | enabled :-) 2015-08-28T22:40:24.000000 |
| |- bcpc-vm2           |                                        |
| | |- nova-compute     | enabled :-) 2015-08-28T22:40:21.000000 |
| |- bcpc-vm3           |                                        |
| | |- nova-compute     | enabled :-) 2015-08-28T22:40:25.000000 |
+-----------------------+----------------------------------------+
root@bcpc-vm1:~# nova boot --flavor m1.tiny --block-device source=image,id=01837847-09cc-4cf1-8fa3-a8986928d887,device=vda,dest=volume,shutdown=remove,bootindex=0,type=SSD,size=10 --availability-zone=TLVM-1 vol_test
[...snip...]
root@bcpc-vm1:~# nova list
+--------------------------------------+----------+--------+----------------------+-------------+-------------------+
| ID                                   | Name     | Status | Task State           | Power State | Networks          |
+--------------------------------------+----------+--------+----------------------+-------------+-------------------+
| edfd028a-ed42-47c3-9faf-db7ecca8e53d | vol_test | BUILD  | block_device_mapping | NOSTATE     | fixed_0=1.127.0.4 |
+--------------------------------------+----------+--------+----------------------+-------------+-------------------+
root@bcpc-vm1:~# nova list
+--------------------------------------+----------+--------+------------+-------------+-------------------+
| ID                                   | Name     | Status | Task State | Power State | Networks          |
+--------------------------------------+----------+--------+------------+-------------+-------------------+
| edfd028a-ed42-47c3-9faf-db7ecca8e53d | vol_test | ACTIVE | -          | Running     | fixed_0=1.127.0.4 |
+--------------------------------------+----------+--------+------------+-------------+-------------------+
```
Additionally, you can verify that the patch behavior is being exercised by checking `/var/log/cinder/cinder-api.log` for a line like this:
```
2015-08-28 22:41:09.877 26540 WARNING cinder.volume.flows.api.create_volume [req-317d005e-7ab0-43de-a143-06cab90b1850 cde09e71fa614cfe94e08c1c511e5084 7b5d7bc342874fedadc79bdb73a52931 - - -] Availability zone 'TLVM-1' not found, falling back to ''
```
(This line will only be printed if requesting an availability zone.)

With `['bcpc']['cinder']['az_fallback']` set to **false**, the above sequence should bail out with an error during the block device mapping phase, as it did without the patch.

Also as before, not specifying an availability zone via `--availability-zone` in the `nova boot` command will work both with and without the patch.

**Comment by erhudy** [comment]
You can also test with any availability zone name in `cinder create`, but Horizon or `nova boot` will require the name of a real compute AZ. `cinder create --availability-zone FDJIFHUDHGUGIGIGDFGJDF` will also verify that the patch is working:
```
root@bcpc-vm1:/var/log/cinder# cinder create --availability-zone JFDIHDIGDFGFD 10
+---------------------+--------------------------------------+
|       Property      |                Value                 |
+---------------------+--------------------------------------+
|     attachments     |                  []                  |
|  availability_zone  |                                      |
|       bootable      |                false                 |
|      created_at     |      2015-08-28T22:47:27.704609      |
| display_description |                 None                 |
|     display_name    |                 None                 |
|      encrypted      |                False                 |
|          id         | f50642b5-95b4-4a2c-8b73-4267996a764c |
|       metadata      |                  {}                  |
|     multiattach     |                false                 |
|         size        |                  10                  |
|     snapshot_id     |                 None                 |
|     source_volid    |                 None                 |
|        status       |               creating               |
|     volume_type     |                 None                 |
+---------------------+--------------------------------------+
root@bcpc-vm1:/var/log/cinder# cinder list
+--------------------------------------+-----------+--------------+------+-------------+----------+--------------------------------------+
|                  ID                  |   Status  | Display Name | Size | Volume Type | Bootable |             Attached to              |
+--------------------------------------+-----------+--------------+------+-------------+----------+--------------------------------------+
| f50642b5-95b4-4a2c-8b73-4267996a764c | available |     None     |  10  |     None    |  false   |                                      |
+--------------------------------------+-----------+--------------+------+-------------+----------+--------------------------------------+
```

**Comment by kamidzi** [comment]
nicely done.
