### PR TITLE
Fixes #1033: fails the Chef run if the host_aggregates provider fails to execute

### LINKED ISSUE #1033: host_aggregates provider does not report failure
If an action with the host_aggregates provider fails, it does not signal failure and the Chef run continues. The Chef run should detonate if something goes wrong when executing a host_aggregates provider action.

### PR DESCRIPTION
**Pull request by erhudy**
This makes the **host_aggregates** provider fail correctly if something goes wrong. You can generally inspire it to blow up by doing something like:

* deleting the maintenance aggregate and recreating it with an attached AZ, then put a node in maintenance, re-chef, take it out of maintenance, re-chef (kaboom)
* possibly putting a node in an AZ it doesn't manage and removing it from a node it does manage will trigger failure
* not sure how to get it to fail when creating an aggregate, though you might be able to simulate that by killing Nova and just running the host-aggregates recipe by itself

### CODE REVIEW

File: cookbooks/bcpc/providers/host_aggregate.rb [hunk 1]
```diff
@@ -37,15 +37,7 @@ def openstack_cli
...
-  if not status.success?
-    converge_by("Creating host aggregate #{new_resource.name}") do
-      args = ["aggregate", "create", @new_resource.name , "-f", "json"]
-      args += ["--zone", "#{@new_resource.zone}"] unless @new_resource.zone.nil?
-      stdout, status = Open3.capture2( *(openstack_cli + args +
-     		                         @new_resource.metadata.collect {|k , v| ["--property", k.to_s + "=" + v.to_s ] }.flatten ))
-      Chef::Log.error "Failed to create host aggregate" unless status.success?
-    end
-  else
+  if status.success?
```
Comment (erhudy) [inline cookbooks/bcpc/providers/host_aggregate.rb]: I flipped the if/else here because having an `if not`/`unless` start a condition block annoys me.

**Comment by kamidzi** [comment]
Could not repro. Could you just write a script to generate the failure?

**Comment by erhudy** [comment]
This worked for me. I built off master, then added this PR and reuploaded the cookbooks. I then did:

vm1
---
```
. /root/adminrc
nova aggregate-delete maintenance
nova aggregate-create maintenance maintenance
```
bootstrap
---
```
EDITOR=vim knife node edit bcpc-vm2.hypervisor-bcpc.example.com
```
(add `"in_maintenance": true,` to the JSON, save)

vm2
---
```
sudo chef-client
```

Should result in
```
    ================================================================================
    Error executing action `member` on resource 'bcpc_host_aggregate[maintenance]'
    ================================================================================
    
    RuntimeError
    ------------
    Failed to add host bcpc-vm2 to aggregate maintenance: ERROR: openstack Cannot add host bcpc-vm2 in aggregate 5: not found (HTTP 404)
```

On master, this should just continue onward (maybe outputting the error message but not terminating the Chef run) because the provider does not stop on failure.

**Comment by kamidzi** [comment]
So essentially, this is to reflect that host_aggregates provider should fail when attempting to add a host to more than one availability zone, which is disallowed?

On master:
```
[2016-06-17T19:54:20+00:00] INFO: Processing bcpc_host_aggregate[maintenance] action depart (bcpc::host-aggregates line 46)
```

**Comment by erhudy** [comment]
The specific thing that is disallowed is having a node in multiple availability zones (as differentiated from aggregates, of which a node may be a member of many). The point of this PR is just to propagate errors returned by the OpenStack clients through to the Chef run as errors that will stop convergence, instead of just printing out an ERROR log message and continuing on.

File: cookbooks/bcpc/providers/host_aggregate.rb [hunk 2]
```diff
@@ -54,13 +46,21 @@ def openstack_cli
     @new_resource.metadata.each { |k,v| new_properties[k.to_s] = v.to_s }
     if new_properties != current_properties
       converge_by ("Update properties") do
-	args = ["aggregate", "set", @new_resource.name]
-	args += ["--zone", "#{@new_resource.zone}"] unless @new_resource.zone.nil?
-	stdout, status = Open3.capture2( *(openstack_cli +
-    	 		 	           args + new_properties.collect {|k , v| ["--property", k + "=" + v ] }.flatten ))
-	Chef::Log.error "Failed to update host aggregate" unless status.success?
+      	args = ["aggregate", "set", @new_resource.name]
```
Comment (kamidzi) [inline cookbooks/bcpc/providers/host_aggregate.rb]: Minor point: extraneous tab characters on this and other lines.

**Comment by erhudy** [comment]
Fixed tab/space confusion on another changeset, can crush if desired.

**Comment by kamidzi** [comment]
Still cannot reproduce error with modified code. Using this bit of hackery: https://gist.github.com/kamidzi/19cb8feab12ea8d62b6b0435c887c6ba

**Comment by erhudy** [comment]
After setting **bcpc.in_maintenance** to true, chef twice before making any further changes. It should fail on the second Chef run.

**Comment by erhudy** [comment]
Or a fresh build with Vagrant 1.8.4 will blow it up. I will review the steps for triggering the failure.

**Comment by erhudy** [comment]
Alright, I was able to cause a failure with the following steps from a fully cheffed-up Liberty build (same should happen on Kilo, but I will need to verify that independently):
* `nova aggregate-delete maintenance` on VM1
* `nova aggregate-create maintenance maintenance` on VM1 (to recreate the **maintenance** zone with an attached AZ)
* set **bcpc.in_maintenance** flag on VM2
* rechef VM2
* unset **bcpc.in_maintenance** flag on VM2
* rechef VM2
* get failure:
```
  * bcpc_host_aggregate[TLVM-1] action member
    
    ================================================================================
    Error executing action `member` on resource 'bcpc_host_aggregate[TLVM-1]'
    ================================================================================
    
    RuntimeError
    ------------
    Failed to add host bcpc-vm2 to aggregate TLVM-1: Cannot add host to aggregate 4. Reason: One or more hosts already in availability zone(s) [u'maintenance']. (HTTP 409) (Request-ID: req-26654ad7-3f05-4baa-b487-07db2554a189)
```

**Comment by erhudy** [comment]
Verified same steps work on Kilo:
```
  * bcpc_host_aggregate[TLVM-1] action member
    
    ================================================================================
    Error executing action `member` on resource 'bcpc_host_aggregate[TLVM-1]'
    ================================================================================
    
    RuntimeError
    ------------
    Failed to add host bcpc-vm2 to aggregate TLVM-1: ERROR: openstack Cannot add host bcpc-vm2 in aggregate 4: host exists (HTTP 409)
```

**Comment by kamidzi** [comment]
Can confirm failure with following mod on test script:
```
--- pr1054.sh.orig      2016-06-21 10:25:31.000000000 -0400
+++ pr1054.sh   2016-06-21 10:09:33.000000000 -0400
@@ -24,7 +24,15 @@
 ' vm-bootstrap

 # re-chef
-vagrant ssh -c 'sudo -i chef-client -obcpc::host-aggregates' vm2
+vagrant ssh -c 'sudo -i chef-client -obcpc::host-aggregates' vm2
+
+# unset
+vagrant ssh  -c '
+knife exec -E "n = Chef::Node.load(\"bcpc-vm2.hypervisor-bcpc.example.com\"); n.normal[\"bcpc\"][\"in_maintenance\"] = false ; n.save ; puts n.normal[\"bcpc\"][\"in_maintenance\"]"
+' vm-bootstrap
+
+# re-chef
+vagrant ssh -c 'sudo -i chef-client -obcpc::host-aggregates' vm2

 # revert
 vagrant ssh  -c '
@@ -43,4 +51,4 @@
 EoF
 '

-vagrant ssh -c 'sudo -i chef-client -obcpc::host-aggregates' vm2
+vagrant ssh -c 'sudo -i chef-client -obcpc::host-aggregates' vm2
```

**Comment by kamidzi** [comment]
Could you sqaush the commits && I'll merge?

**Comment by erhudy** [comment]
Squashed.
